var EXPORTED_SYMBOLS = ["cipherSuites", "cipherStrength"];

const cipherSuites = [

    { name: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",  rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_RSA_WITH_AES_256_GCM_SHA384",      rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",  rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_RSA_WITH_AES_256_CBC_SHA256",      rank: 10, pfs: 0, notes: "Strong" }, 
    { name: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",   rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA",    rank: 10, pfs: 0, notes: "Strong" }, 
    { name: "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA",  rank: 10, pfs: 0, notes: "Strong" }, 
    { name: "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA", rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA", rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA",    rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",     rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_DHE_DSS_WITH_AES_256_CBC_SHA",     rank: 10, pfs: 1, notes: "Strong" }, 
    { name: "TLS_RSA_WITH_AES_256_CBC_SHA",         rank: 10, pfs: 0, notes: "Strong" }, 
    { name: "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",  rank: 9, pfs: 1, notes: "168 bit" },
    { name: "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA",    rank: 9, pfs: 1, notes: "168 bit" }, 
    { name: "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA",    rank: 9, pfs: 1, notes: "168 bit" },
    { name: "TLS_RSA_WITH_3DES_EDE_CBC_SHA",        rank: 9, pfs: 0, notes: "168 bit" }, 
    { name: "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA", rank: 9, pfs: 0, notes: "168 bit" },
    { name: "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA", rank: 9, pfs: 0, notes: "168 bit" },
    { name: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",rank: 8, pfs: 1, notes: "128 bit" }, 
    { name: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", rank: 8, pfs: 1, notes: "128 bit" }, 
    { name: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",rank: 8, pfs: 1, notes: "128 bit" }, 
    { name: "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",  rank: 8, pfs: 1, notes: "128 bit" }, 
    { name: "TLS_RSA_WITH_AES_128_GCM_SHA256",      rank: 8, pfs: 0, notes: "128 bit" }, 
    { name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",  rank: 8, pfs: 0, notes: "128 bit" }, 
    { name: "TLS_RSA_WITH_AES_128_CBC_SHA256",      rank: 8, pfs: 0, notes: "128 bit" }, 
    { name: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",   rank: 8, pfs: 1, notes: "128 bit" }, 
    { name: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA",    rank: 8, pfs: 0, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA",  rank: 8, pfs: 0, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",     rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_ECDHE_RSA_WITH_RC4_128_SHA",       rank: 8, pfs: 1, notes: "RC4 considered unsafe. SHA-1 reportedly weak." }, 
    { name: "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",     rank: 8, pfs: 1, notes: "RC4 considered unsafe. SHA-1 reportedly weak." }, 
    { name: "TLS_ECDH_ECDSA_WITH_RC4_128_SHA",      rank: 8, pfs: 0, notes: "RC4 considered unsafe. SHA-1 reportedly weak." }, 
    { name: "TLS_ECDH_RSA_WITH_RC4_128_SHA",        rank: 8, pfs: 0, notes: "RC4 considered unsafe. SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_RSA_WITH_SEED_CBC_SHA",        rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_RSA_WITH_SEED_CBC_SHA",            rank: 8, pfs: 0, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA", rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA", rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA", rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",     rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",     rank: 8, pfs: 1, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_RSA_WITH_AES_128_CBC_SHA",         rank: 8, pfs: 0, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA",    rank: 8, pfs: 0, notes: "SHA-1 reportedly weak." }, 
    { name: "TLS_RSA_WITH_RC4_128_SHA",             rank: 6, pfs: 0, notes: "RC4 considered unsafe. SHA-1 reportedly weak." }, 
    { name: "SSL_RSA_WITH_RC4_128_SHA",             rank: 6, pfs: 0, notes: "RC4 considered unsafe. SHA-1 reportedly weak." }, 
    { name: "TLS_RSA_WITH_RC4_128_MD5",             rank: 5, pfs: 0, notes: "RC4 considered unsafe. MD5 is broken." }, 
    { name: "SSL_RSA_WITH_RC4_128_MD5",             rank: 5, pfs: 0, notes: "RC4 considered unsafe. MD5 is broken." }, 
    { name: "TLS_DHE_RSA_WITH_DES_CBC_SHA",         rank: 4, pfs: 1, notes: "Very weak, 56 bit" }, 
    { name: "TLS_RSA_WITH_DES_CBC_SHA",             rank: 4, pfs: 0, notes: "Very Weak, 56 bit" },
    { name: "TLS_EMPTY_RENEGOTIATION_INFO_SCSV",    rank: 0, pfs: 0, notes: "?" } 
]; 

const cipherStrength = {
    MAX: 10, 
    HIGH: 7, 
    MEDIUM: 5, 
    LOW: 0
}; 

